name: Test Email Action

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1001237@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"

